/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthRouteRouteImport } from './routes/_auth/route';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthLiveRouteImport } from './routes/_auth/live';
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings';
import { Route as AuthStreamCodeRouteImport } from './routes/_auth/stream/$code';
import { Route as AuthWatchCodeRouteImport } from './routes/_auth/watch/$code';
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const AuthRouteRoute = AuthRouteRouteImport.update({
    id: '/_auth',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const AuthLiveRoute = AuthLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthRouteRoute,
});
const AuthSettingsRoute = AuthSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthRouteRoute,
});
const AuthStreamCodeRoute = AuthStreamCodeRouteImport.update({
    id: '/stream/$code',
    path: '/stream/$code',
    getParentRoute: () => AuthRouteRoute,
});
const AuthWatchCodeRoute = AuthWatchCodeRouteImport.update({
    id: '/watch/$code',
    path: '/watch/$code',
    getParentRoute: () => AuthRouteRoute,
});
const AuthRouteRouteChildren = {
    AuthLiveRoute: AuthLiveRoute,
    AuthSettingsRoute: AuthSettingsRoute,
    AuthStreamCodeRoute: AuthStreamCodeRoute,
    AuthWatchCodeRoute: AuthWatchCodeRoute,
};
const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AuthRouteRoute: AuthRouteRouteWithChildren,
    LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
